trigger:
- main

variables:
  azureSubscription: '6fe734cc-3f4f-4a31-80ba-59dab1195e36'
  webAppName: 'app-reg-sys'
  vmImageName: 'ubuntu-latest'
  phpVersion: '8.3'
  environmentName: 'app-reg-sys'
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)

    steps:
    - script: |
        set -e

        sudo update-alternatives --set php /usr/bin/php$(phpVersion)
        sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
        php -v
        php -r "exit(version_compare(PHP_VERSION, '8.3.0', '>=') ? 0 : 1);"
        composer --version
      workingDirectory: $(rootFolder)
      displayName: 'Use PHP version $(phpVersion)'

    - script: |
        set -e
        composer validate --no-check-publish
        composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      workingDirectory: $(rootFolder)
      displayName: 'Composer install'

    - task: CopyFiles@2
      displayName: 'Stage deploy files'
      inputs:
        SourceFolder: '$(rootFolder)'
        Contents: |
          app/**
          bootstrap/app.php
          bootstrap/providers.php
          config/**
          database/**
          public/**
          resources/views/**
          routes/**
          storage/app/public/**
          artisan
          composer.json
          composer.lock
          vendor/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)/app'
        CleanTargetFolder: true

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy Azure Web App : app-reg-sys'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        appType: webAppLinux
        package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
