<?php

return [
    'NO FORMAL EDUCATION',
    'ELEMENTARY UNDERGRADUATE',
    'ELEMENTARY GRADUATE',
    'JUNIOR HIGH SCHOOL UNDERGRADUATE',
    'JUNIOR HIGH SCHOOL GRADUATE',
    'HIGH SCHOOL LEVEL (NON K-12)',
    'HIGH SCHOOL GRADUATE (NON K-12)',
    'SENIOR HIGH SCHOOL UNDERGRADUATE',
    'SENIOR HIGH SCHOOL GRADUATE',
    'VOCATIONAL UNDERGRADUATE',
    'VOCATIONAL GRADUATE',
    'COLLEGE UNDERGRADUATE',
    'COLLEGE GRADUATE',
    "BACHELOR'S DEGREE",
    'POSTGRADUATE',
    "MASTER'S DEGREE",
    'DOCTORATE DEGREE',
];
