<?php

return [
    'city_governments' => [
        'ALFONSO',
        'AMADEO',
        'CITY OF BACOOR',
        'CITY OF CALOOCAN',
        'CITY OF CARMONA',
        'CITY OF CAVITE',
        'CITY OF DASMARINAS',
        'GENERAL EMILIO AGUINALDO',
        'GENERAL MARIANO ALVAREZ',
        'CITY OF GENERAL TRIAS',
        'INDANG',
        'CITY OF IMUS',
        'KAWIT',
        'CITY OF LAS PINAS',
        'MAGALLANES',
        'CITY OF MAKATI',
        'CITY OF MALABON',
        'CITY OF MANDALUYONG',
        'CITY OF MANILA',
        'MARAGONDON',
        'CITY OF MARIKINA',
        'MENDEZ',
        'CITY OF MUNTINLUPA',
        'NAIC',
        'CITY OF NAVOTAS',
        'NOVELETA',
        'PATEROS',
        'CITY OF PARANAQUE',
        'CITY OF PASAY',
        'CITY OF PASIG',
        'CITY OF QUEZON CITY',
        'ROSARIO',
        'CITY OF SAN JUAN',
        'SILANG',
        'CITY OF TAGAYTAY',
        'CITY OF TAGUIG',
        'TANZA',
        'TERNATE',
        'CITY OF TRECE MARTIRES',
        'CITY OF VALENZUELA',
    ],
];
